django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('shoppy.urls')),
    path('admin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('', views.home, name='shoppy-home'),

   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list/<int:category_id>/', views.productsList, name='product_list'),
   path('allcategoryproductsList/', views.allcategoryproductsList, name='allcategoryproductsList'),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),
   path('placeholder/' , views.placeholder, name="placeholder" ),

   path('howtopay/', views.how_to_pay, name='how_to_pay'),

   path('product_filter/', views.product_filter, name='product_filter'),





   #wishlist
   path('add_to_wishlist/' , views.addToWishlist, name='add_to_wishlist' ),
   path('add_to_wishlist2/<int:product_id>/<str:source>/' , views.addToWishlist2, name='add_to_wishlist2' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         # path('make_reviews/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<str:source>/', views.addCart, name='shoppy-add-cart'),
   # path('addto/cartsession/', views.addCartSession, name='shoppy-add-cartSession'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset

   path('pin_reset/', views.password_resett, name='password_resett'),
   path('getpinShortcode/', views.getShortcode, name='getpinShortcode'),
   path('verifyCode/', views.verifyCode, name='verifyCode'),
   path('verifypassword/', views.verifypassword, name='verifypassword'),
   path('pin_confirm/', views.pin_confirmm, name='password_confirmm'),
   path('new_pin/', views.new_pin, name='new_pin'),




   path('deleteme/', views.deleteme, name= 'deleteme'),
   path('check_voucher_if_it_exists/', views.check_voucher_if_it_exists, name= 'check_voucher_if_it_exists'),


   path('all_buyers_orders/', views.all_buyers_orders, name= 'all_buyers_orders'),
   path('all_buyers_order_products/<str:reference_code>', views.all_buyers_order_products, name= 'all_buyers_order_products'),
   path('orders_payment_opions/<int:checkout_id>', views.orders_payment_opions, name= 'orders_payment_opions'),





]

shoppyadmin/urls.py
from django.urls import path
from .views import GeneratePDF, ListUsers, GenerateProductPDF,  ListOrdersadmin

from . import views

app_name = 'ShoppyAdmin'
urlpatterns = (

   path('', views.home, name='shoppy-admin-home'),
   path('sellers/', views.sellers, name='shoppy-admin-sellers'),
   path('orders/', views.orders, name='shoppy-admin-orders'),
   path('login/', views.user_login, name='shoppy-admin-login'),
   path('all/productsreviews/', views.reviews, name='shoppy-admin-reviews'),
   path('singleproduct/review/<int:product_id>/', views.single_product_review, name='single_product_review'),
   path('buyers/', views.buyers, name='shoppy-admin-buyers'),
   path('useraccount/', views.userAccount, name='shoppy-user-account'),
   path('adminaccount/', views.adminAccount, name='shoppy-admin-account'),
   path('useraccount/changepassword/', views.changepassword, name='shoppy-changepassword'),

   path('payments/', views.payments, name='shoppy-payments'),
   path('editpayments/<int:Order_payment_id>', views.edit_payments, name='shoppy_updated_payments'),
   path('buyerOrders/<str:reference_code>', views.buyerOrders, name='shoppy-buyer_orders'),
   path('buyerOrdersCancel/<str:reference_code>', views.buyerOrdersCancel, name='shoppy-buyer_orders_cancel'),
     # extras
      path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
      path('xcel/orders/', views.export_users_xls, name='export_users_xl'),
      path('xcel/orders/date', views.export_users_xls_date, name='export_users_xl_date'),
      path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),
      path('users/chart/', ListUsers.as_view(), name='users_chart'),
      path('orders/chart/', views.ListOrders, name='orders_chart'),
      path('orders/chart/admin', ListOrdersadmin.as_view(), name='orders_chartadmin'),
     # extras
   # seller
   path('seller_status/<int:seller_id>', views.sellerStatusChange, name='shoppy-admin-status-change'),

   #products
   path('view/products/', views.view_all_products, name="shoppy_admin_view_all_products"),
   path('view/all/products/', views.view_products, name="view_products"),
   # path('filter_products/', views.fillter_products_per_seller, name="fillter_products_per_seller"),

   path('edit/product/<int:product_id>', views.edit_product, name="shoppy_admin_edit_product"),
   path('delete/product/<int:product_id>', views.product_delete, name='product_delete'),

   #featuredProducts
   path('products/featured/products', views.featured_products, name='featuredproduct'),
   path('featured/product/change/status/featured/<int:product_id>', views.featured_products_featured, name='featured_products'),
   path('featured/product/change/status/normal/<int:product_id>', views.normal_products_normal, name='nomal_products'),
   path('featured/product/change/status/', views.product_featured, name='product_featured'),

   path('products/verified/<int:product_id>/', views.verify_product, name='verify_product'),
   path('products/unverified/<int:product_id>/', views.unverify_product, name='unverify_product'),
   path('products/verification/', views.product_verification, name='product_verification'),

   #category
   path('view_category/', views.view_category, name='shoppy_admin_add_category'),
   path('addingcategory/', views.addingcategory, name='shoppy_adding_category'),
   path('deletecategory/<int:category_id>', views.deletecategory, name='shoppy_delete_category'),
   path('editcategory/<int:category_id>', views.editcategory, name='shoppy_edit_category'),
   path('view_sub_category/<int:category_id>', views.view_sub_category, name='shoppy_view_sub_category'),


   # brand
   path('add_brand/', views.add_brand, name='shoppy_admin_add_brand'),
   path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
   path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),

   #image
   path('delete/image/<int:image_id>', views.image_delete, name='delete_product_image'),

   #regions
   path('viewregions/', views.view_regions, name='shoppy-admin-view-regions'),
   path('regions/edit/<int:region_id>', views.edit_regions, name='shoppy-admin-edit-regions'),
   path('regions/delete/<int:region_id>', views.delete_regions, name='shoppy-admin-delete-regions'),

   #carousell
   path('view/carousel/', views.view_carousel, name='view_carousel'),
   path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),
   path('carousel/edit/<int:carousel_id>', views.carousel_edit, name='carousel-edit'),

   #variants
   path('variants/', views.variants, name='variants'),
   path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
   path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   #variant options
   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

   # offer
   path('offers/', views.offer, name='view_product_offer'),
   path('addOffer/',views.addOffer, name="adding_offers"),
   path('editOffer/<int:offer_id>',views.editOffer, name="edit_offers"),
   path('deleteOffer/<int:offer_id>',views.deleteOffer, name="delete_offer"),

   # reports
   path('allreports/', views.viewAllReports, name='view_all_reports'),

   #inventory
   path('updateInventory/<int:product_id>', views.update_Inventory, name='updateInventory'),
   # voucher
   path('voucher/', views.voucher, name='voucher'),
   path('addvoucher/', views.addvoucher, name='addvoucher'),
   path('deletevoucher/<int:voucher_id>', views.deletevoucher, name='deletevoucher'),
   path('editvoucher/<int:voucher_id>', views.editvoucher, name='editvoucher'),

)

shoppyadmin/models.py
from django.db import models

# Create your models here.

shoppyadmin/templates/aaa_layout.html
<!DOCTYPE html>
{% load static %}
{% load call_method %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% if title %}
       <title>Mashkys</title>
    {% else %}
        <title>Mashkys</title>
    {% endif %}
    <link rel="icon" type="image/png" href="{% static 'sitelogo/favicone.png' %}"/>



    {#    preloader css#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="{% static 'css/preloadercss/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    {#end-preloadercss#}
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    {% block links %}

    {% endblock links %}
    <!--[if lt IE 9]>
    <![endif]-->
</head>
<body style="zoom: 76% !important;">
    {#preloader#}
{#    <header class="loader_wrapper">#}
{#        <div class='body'>#}
{#        <span>#}
{#          <span></span>#}
{#          <span></span>#}
{#          <span></span>#}
{#          <span></span>#}
{#        </span>#}
{#        <div class='base'>#}
{#          <span></span>#}
{#          <div class='face'></div>#}
{#        </div>#}
{#      </div>#}
{#      <div class='longfazers'>#}
{#        <span></span>#}
{#        <span></span>#}
{#        <span></span>#}
{#        <span></span>#}
{#      </div>#}
{#      <h1 class="loading_text">Loading Mashkys Admin</h1>#}
{#    </header>#}
    {#endpreloader#}
    <div class="col-sm-12 col-md-12 col-lg-12">
         <nav style="margin: 0;" class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand logo-admin" href="{% url 'ShoppyAdmin:shoppy-admin-home' %}">
                    <img style="height: 61px;width: 202px;" src="{% static 'images/siteimages/full_colour_logo_no_tagline.png' %}" alt="">
                </a>
                <div class="dropdown pull-right">
                  <button style="" class="username dropdown-toggle " type="button" data-toggle="dropdown">
                      {% if request.user.is_authenticated %}
                          {% if not request.user|is_seller %}
                             Hi Admin
                          {% else %}
                             Hi {{ request.user.first_name }}
                          {% endif %}
                      {% else %}
                        <span class="">
                            <i class="fas fa-user-alt"></i>
                        </span>
                      {% endif %}
                      <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-custom" role="menu" aria-labelledby="menu1">
                    <li role="presentation" ><a class="" role="menuitem" href="{% url 'ShoppyAdmin:shoppy-user-account' %}">My account</a></li>
                    <li role="presentation" ><a class="" role="menuitem" href="{% url 'ShoppyAdmin:shoppy-changepassword' %}"> Bad password</a></li>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation"><a  class="btn login-btn color-white" role="menuitem" href="{% url 'Shoppy:shoppy-logout' %}">Logout</a></li>
                  </ul>
                </div>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
    </div>

	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">

		<div class="divider" style="margin-bottom: 130px;"></div>

		<ul class="nav menu">
            <li><a href="{%  url 'ShoppyAdmin:shoppy-admin-home' %}"><em class="fas fa-tachometer-alt">&nbsp;</em> Dashboard</a></li>
            <li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-orders' %}"><em class="fa fa-toggle-off">&nbsp;</em> Orders</a></li>

			<li class="parent">
                <a  data-toggle="collapse" href="#productssubmenus">
				     <em class="fas  fa-capsules ">&nbsp;</em>
                        Products
                     <span data-toggle="collapse" href="#productssubmenus" class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="productssubmenus">
					<li><a class="" href="{% url 'ShoppyAdmin:view_products' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> View Products
					</a></li>
{#                    {% if not request.user|is_seller %}#}
					<li><a class="" href="{% url 'ShoppyAdmin:featuredproduct' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Featured Products
					</a></li>
{#                    {% endif %}#}

                    <li><a class="" href="{% url 'ShoppyAdmin:view_product_offer' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Product Offer
					</a></li>

                    {% if request.user|is_seller %}
                    <li>
                        <a class="" href="{% url 'ShoppyAdmin:variants' %}">
                            <span class="fa fa-arrow-right">&nbsp;</span> Variants
                        </a>
                    </li>
                    <li>
                        <a class="" href="{% url 'ShoppyAdmin:voucher' %}">
                            <span class="fa fa-arrow-right">&nbsp;</span> Voucher
                        </a>
                    </li>

                    {% endif %}
                    {% if not request.user|is_seller %}
                    <li><a class="" href="{% url 'ShoppyAdmin:view_carousel' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Advertisement
					</a></li>

                    {% endif %}
				</ul>
			</li>
             {% if request.user|is_seller %}
                <li class=""><a href="{% url 'ShoppyAdmin:shoppy-payments' %}"><em class="fa fa-money-bill-alt">&nbsp;</em> Payments</a></li>
            {% endif %}
            {% if not request.user|is_seller %}
                <div class="divider" style="margin-bottom: 20px; border: 1px solid white; background-color: white;"></div>
                <li class="parent">
                    <a  href="{% url 'ShoppyAdmin:shoppy_admin_add_brand'  %}">
                         <em class="fas fa-file-alt">&nbsp;</em>
                            Brands
                    </a>

                </li>
                <li class="parent">
                    <a href="{% url 'ShoppyAdmin:shoppy_admin_add_category' %}">
                         <em class="fas fa-file-alt">&nbsp;</em>
                            Category
                    </a>
                </li>
                <li class=""><a href="{%  url 'ShoppyAdmin:shoppy-admin-buyers' %}"><em class="fas fa-user">&nbsp;</em> Buyers</a></li>
                <li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-sellers' %}"><em class="fas fa-users">&nbsp;</em> Sellers</a></li>
			{% endif %}
            {% if request.user|is_seller %}
{#            <div class="divider" style="margin-bottom: 20px; border: 1px solid white; background-color: white;"></div>#}
			<li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-view-regions' %}"><em class="fa fa-map-marked">&nbsp;</em> Delivery Regions</a></li>

                <div class="divider" style="margin-bottom: 20px; border: 1px solid white; background-color: white;"></div>
			<li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-reviews' %}"><em class="fas fa-file-signature">&nbsp;</em> Reviews</a></li>
{#            <li class=""><a href="{% url 'ShoppyAdmin:shoppy-payments' %}"><em class="fas fa-money-bill-alt">&nbsp;</em> Payments</a></li>#}
            {% endif %}
{#            <li class="parent">#}
{#                <a data-toggle="collapse" href="#reports">#}
{#				     <em class="fas fa-file-pdf">&nbsp;</em>#}
{#                        Reports#}
{#                     <span data-toggle="collapse" href="#reports" class="icon pull-right">#}
{#                         <em class="fa fa-plus"></em>#}
{#                     </span>#}
{#				</a>#}
{#				<ul class="children collapse" id="reports">#}
{#					<li><a class="" href="{% url 'ShoppyAdmin:view_all_reports' %}">#}
{#						<span class="fa fa-arrow-right">&nbsp;</span> View Reports#}
{#					</a></li>#}
{#				</ul>#}
{#			</li>#}

			<li class=""><a href="{% url 'Shoppy:shoppy-logout' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
		</ul>
	</div><!--/.sidebar-->
    <div style=" position: absolute; z-index: 9;" class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" >
        <div class="row " style="margin: 10px 0">
                {% if messages %}
                 <div class="" style="height: 42px; ">
                    <div class="">
                        <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <ul class="messages w-100">
                                      {% for message in messages %}
                                          <div class="alert {% if message.tags == 'error' %}alert-danger{% endif %}
                                                   {% if message.tags == 'success' %}alert-success{% endif %}
                                                   {% if message.tags == 'info' %}alert-info{% endif %}
                                                   alert-dismissible fade-in">
                                              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                              <span class="text-white {% if message.tags %} {{ message.tags }}{% endif %}" >
                                                  <strong class="text-capitalize">
                                                  {% if message.tags %} {{ message.tags }} {% endif %}!
                                                  </strong> {{ message }}
                                              </span>
                                          </div>
                                      {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
           {% endif %}
            </div><!--/.row-->
    </div>
    {% block content %}



    {% endblock %}


	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
    <script>
       $(window).on("load", function () {

            setTimeout(function(){
               $(".loader_wrapper").removeClass("loadingslideright").addClass("loadingslideleft")
            }, 2000);
        })
    </script>

    {% block scripts %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    {% load sweetify %}
    {% sweetify %}
</body>
</html>

shoppyadmin/templates/invoice.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Orders</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .text-capitalize{
                text-transform: capitalize;
            }

            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
            .product-image{
                width: 90px;
                height: 90px;
                overflow: hidden;
                border-radius: 10px;
                margin: 0;
                border: 1px solid black;
            }
            .product-image img{
                width: 100%;
                height: 100%;
                background-position: center;
                background-size: cover;
                border-radius: 10px;
            }
        </style>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        {% load static %}
        {% load humanize %}
    </head>

    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Orders ({{ orders.count }}) </p>
            </div>
            <div>
                <img src="{% static 'sitelogo/websitetitlelogo.png' %}" alt="">
            </div>
        <div>
        <div class="details">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Img</th>
                  <th scope="col">Product Name</th>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Phone number</th>
                  <th scope="col">Quantity</th>

                  <th scope="col">Cost</th>
                </tr>
              </thead>
              <tbody>
                {% for order in orders %}
                    <tr>
                      <th scope="row">{{ order.id }}</th>
                      <td>
                          <div class="product-image">
                              <img src="../../{{ order.product.featured_url.url }}" alt="image"/>
                          </div>
                      </td>
                      <td class="text-capitalize">{{ order.buyer.first_name }}</td>
                      <td class="text-capitalize">{{ order.buyer.last_name }}</td>
                      <td>{{ order.buyer.phone_number }}</td>
                      <td>{{ order.quantity }}</td>

                      <td colspan="2">{{ order.total|floatformat:2|intcomma }} Ksh</td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
        </div>
        </div>
        </div>
    </body>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</html>

shoppyadmin/templates/sellers.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
     <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">

{% endblock %}
{% block content %}

		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-home"></em>
				</a></li>
				<li class="active">Sellers</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Sellers</h1>
			</div>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						Sellers

						<span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
					<div class="panel-body">
						<div class="canvas-wrapper">
							<div class="main-chart" id="line-chart" height="200" width="600">
                                <table id="example" class="example table table-striped table-bordered" style="width:100%;">
                                    <thead >
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Logo</th>
                                            <th>Name</th>
                                            <th>Business_No</th>
                                            <th>Store_name</th>
                                            <th>Status</th>
                                            <th>County</th>
                                            <th>Created At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         {% for seller in seller %}
                                            <tr class="text-center ">
                                                <td class="tb-data">{{ seller.id }}</td>
                                                <td class="tb-data tb-data">
                                                    <div class="store-logo-image">
                                                       <img src="{{ seller.store_logo.url }}" alt="">
                                                    </div>
                                                </td>
                                                <td class="product-details">{{ seller.first_name }} {{ seller.last_name }}</td>
                                                <td class="tb-data">{{ seller.business_no }}</td>
                                                <td class="tb-data">{{ seller.store_name }}</td>
                                                <td class="tb-data">{{ seller.status }}</td>
                                                <td class="tb-data">{{ seller.country }}</td>
                                                <td class="tb-data">{{ seller.date_joined|date:'Y-m-d[H:i]'  }}</td>
                                                <td class="text-center tb-data" width="296">
                                                    <a href="#" class="btn btn-info"><i class="fas fa-eye"></i> View</a>
                                                    <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                                                    {% if seller.status == 'UNVERIFIED' %}
                                                    <a href="{% url 'ShoppyAdmin:shoppy-admin-status-change' seller.id %}" class="btn btn-success"><i class="fas fa-plus"></i> Activate</a>
                                                    {% else %}
                                                    <a href="{% url 'ShoppyAdmin:shoppy-admin-status-change' seller.id %}" class="btn btn-brown"><i class="fas fa-pencil-alt"></i> Deactivate</a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                         {% endfor %}
                                    </tbody>
                                </table>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
	</div>	<!--/.main-->
	  




{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('.example').DataTable();
        } );
    </script>

    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock %}