django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('shoppy.urls')),
    path('admin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('', views.home, name='shoppy-home'),

   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list/<int:category_id>/', views.productsList, name='product_list'),
   path('allcategoryproductsList/', views.allcategoryproductsList, name='allcategoryproductsList'),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),
   path('placeholder/' , views.placeholder, name="placeholder" ),

   path('howtopay/', views.how_to_pay, name='how_to_pay'),

   path('product_filter/', views.product_filter, name='product_filter'),





   #wishlist
   path('add_to_wishlist/' , views.addToWishlist, name='add_to_wishlist' ),
   path('add_to_wishlist2/<int:product_id>/<str:source>/' , views.addToWishlist2, name='add_to_wishlist2' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         # path('make_reviews/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<str:source>/', views.addCart, name='shoppy-add-cart'),
   # path('addto/cartsession/', views.addCartSession, name='shoppy-add-cartSession'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset

   path('pin_reset/', views.password_resett, name='password_resett'),
   path('getpinShortcode/', views.getShortcode, name='getpinShortcode'),
   path('verifyCode/', views.verifyCode, name='verifyCode'),
   path('verifypassword/', views.verifypassword, name='verifypassword'),
   path('pin_confirm/', views.pin_confirmm, name='password_confirmm'),
   path('new_pin/', views.new_pin, name='new_pin'),




   path('deleteme/', views.deleteme, name= 'deleteme'),
   path('check_voucher_if_it_exists/', views.check_voucher_if_it_exists, name= 'check_voucher_if_it_exists'),


   path('all_buyers_orders/', views.all_buyers_orders, name= 'all_buyers_orders'),
   path('all_buyers_order_products/<str:reference_code>', views.all_buyers_order_products, name= 'all_buyers_order_products'),
   path('orders_payment_opions/<int:checkout_id>', views.orders_payment_opions, name= 'orders_payment_opions'),





]

shoppy/views.py
import json
import os

import sweetify
from androidAuthApi.models import ShortCode
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q, Max
from django.http import JsonResponse
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib.auth import authenticate, logout, login, get_user_model
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
import africastalking
from django.views.decorators.csrf import csrf_exempt
from requests import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny


from .forms import *


# Create your views here.

# # Base method with no type specified
# sweetify.sweetalert(self.request, 'Westworld is awesome', text='Really... if you have the chance - watch it!' persistent='I agree!')
#
# # Additional methods with the type already defined
# sweetify.info(self.request, 'Message sent', button='Ok', timer=3000)
# sweetify.success(self.request, 'You successfully changed your password')
# sweetify.error(self.request, 'Some error happened here - reload the site', persistent=':(')
# sweetify.warning(self.request, 'This is a warning... I guess')




def search(request):

    if request.method=="POST":
        search_text = request.POST['search_text']
        print(search_text)
    else:
        search_text =""

    products = Product.objects.filter(name__contains=search_text, status='VERIFIED' )
    context={
        'products': products,
        'search_text': search_text,
    }
    return render_to_response('shoppy/search.html',context)

def placeholder(request):

    product =Product.objects.order_by("?").first()
    context={
        'product':product.name,
    }
    return JsonResponse(context)

def home(request):
    user = request.user
    carousels =Carousel.objects.order_by("-created_at")
    brand = Brand.objects.order_by('?').last()
    category = Category.objects.order_by('?').first()
    products = Product.objects.order_by("?")
    featured_products = Product.objects.filter(feat_product='FEATURED', status='VERIFIED')
    products_all = Product.objects.filter(status='VERIFIED').order_by('?')
    # brand_products_greater_than_14 = Product.objects.filter(bra)
    wishlist_count = Wishlist.objects.filter(buyer_id=request.user.id).count()

    side_carousel_product = Product.objects.order_by("?")
    if Product.objects.filter(category_id=category.id).order_by("?").count() >= 18:
        brand_products = Product.objects.filter(category_id=category.id).order_by("?")
    else:
        brand_products = Product.objects.order_by("-created_at")

    # mod = os.path.dirname(__file__)
    # file = os.path.join(mod, 'county.json')
    #
    # with open(file) as f:
    #     print()
    #     data = f.read()
    #     # print(data.split('¿', 1)[1])
    #     json_data = json.loads(data.split('¿', 1)[1])
    #
    #     for p in json_data:
    #         County.objects.create(
    #            number=p['county_number'],
    #            name=p['county']
    #
    #         )
            # print(p['county_number'], p['county'])


    context ={
        'title':'Mashkys',
        'user': user,
        'carousels' : carousels,
        'featured_products': featured_products,
        # 'products': products,
        'product_brands':brand_products,
        'productsaz':products_all,
        'wishlist_count':wishlist_count,
        'brand':brand,
        'side_carousel_product':side_carousel_product,
        # 'categories':categories,
        # 'orderproducts': orderproducts
    }
    return render(request, 'shoppy/home.html', context)




@csrf_exempt
@login_required()
def addToWishlist(request):
    if request.method=="POST" and request.is_ajax():
        product_id = request.POST.get("product_id")

        product = Product.objects.filter(id=product_id).first()
        buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()

        order = Order_Product.objects.filter(product=product, buyer=buyer, checkout__isnull=True).first()
        if not Wishlist.objects.filter(buyer=buyer, product=product).exists():

            order.delete()
            Wishlist.objects.create(
                buyer=buyer,
                product=product
            )

            context={
                "results":"add_success",
                "wishlist_count": Wishlist.objects.filter(buyer=buyer).count(),
                "message": 'Added successfully',
            }
        else:
            wishlist = Wishlist.objects.filter(buyer=buyer, product=product).first()
            wishlist.delete()
            context = {
                "results": "deleted_success",
                "wishlist_count": Wishlist.objects.filter(buyer=buyer).count(),
                "message": 'Wish Removed successfully',
            }
        return JsonResponse(context)


@login_required()
def unWishProduct(request, wishlist_id, source):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.filter(id=wishlist_id)
    if buyer is not None:
        wishlist.delete()
        sweetify.success(request,  'Your Wish Have Been Removed', button='ok', timer=3000)
        # messages.success(request, '')
    source = source.replace('____', '/')
    return redirect(source)


@login_required()
def unWish_All_Products(request):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.all().filter(buyer_id=request.user.id)
    if buyer is not None:

        wishlist.delete()
        sweetify.success(request,  'All Your Wishes Have Been Removed',
button='ok', timer=3000)
        # messages.success(request, '')
    return redirect('Shoppy:shoppy-user_account')

# cart
def cart(request):

    if request.method == 'GET':
        cookie = request.COOKIES.get('Mashkys', False)
        mash_cookie = MashCartCookie.objects.filter(mashcookie__exact=cookie).first()
        # print(mash_cookie)
        order_varianto = OrderProductVariantOption.objects.all()
        buyer =  Buyer.objects.filter(user_ptr_id=request.user.id).first()
        if request.user.is_authenticated:
            carts = Order_Product.objects.filter(buyer=buyer , checkout__isnull=True)
        else:
            carts = Order_Product.objects.filter(session=mash_cookie, checkout__isnull=True, buyer_id__isnull=True ).all()


        total = 0
        for order_product in Order_Product.objects.filter(session=mash_cookie, checkout_id__isnull=True):
            total += float(order_product.total)





        context = {
            'carts' :carts,
            'title': 'Shoppy-Cart',
            'ordervarianto': order_varianto,
            'buyer':buyer,
            'total':total,
        }
        return render(request, 'shoppy/cart.html', context)




def addCart(request, source):
    source = source.replace('____', '/')
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    if request.method == 'POST':

        quantity = request.POST.get('quantity')
        product_id = request.POST.get('product')
        cookie_data = request.POST.get('cookie')
        total = (float(request.POST.get('unit_cost')) * int(quantity))
        request.POST = request.POST.copy()
        request.POST['buyer'] = buyer
        options = request.POST.getlist('variant_options[]')
        if not request.user.is_authenticated:
            product = Product.objects.filter(id=product_id).first()
            if not MashCartCookie.objects.filter(mashcookie__iexact=cookie_data).exists():
                newmashCookie = MashCartCookie.objects.create(
                    mashcookie=cookie_data,
                )
                orderProduct =Order_Product.objects.create(
                    product_id=product.id,
                    total=total,
                    quantity=quantity,
                    session=newmashCookie,
                )
                if options is not None:
                    for variantoption in options:
                        variant_option = Variant_Option.objects.filter(id=variantoption).first()
                        OrderProductVariantOption.objects.create(
                            variantOptions=variant_option,
                            orderProduct=orderProduct,
                        )
                sweetify.success(request, title='Success' 'Product Added To Cart', button='ok', timer=3000)
                return redirect(source)

            else:
                existingmashcookie = MashCartCookie.objects.filter(mashcookie__iexact=cookie_data).first()
                if not Order_Product.objects.filter(session=existingmashcookie , product=product).exists():
                    orderProduct =Order_Product.objects.create(
                        product_id=product.id,
                        total=total,
                        quantity=quantity,
                        session=existingmashcookie,
                    )
                    if options is not None:
                        for variantoption in options:
                            variant_option = Variant_Option.objects.filter(id=variantoption).first()
                            OrderProductVariantOption.objects.create(
                                variantOptions=variant_option,
                                orderProduct=orderProduct,
                            )

                    sweetify.success(request, title='Success' 'Product Added To Cart', button='ok', timer=3000)
                    return redirect(source)
                else:
                    sweetify.error(request, title='Erroe' 'Error Adding Product To Cart', button='ok', timer=3000)
                    return redirect(source)

        else:

shoppy/templates/shoppy/cart.html
{% extends 'shoppy/layout.html' %}
{% load static %}
{% load call_method %}
{% load humanize %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/cart_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop.css' %}">
    <link rel="stylesheet" href="{% static 'css/product_card.css' %}">
{% endblock links %}
{% block content %}

    <div class="col-sm-12 row px-5 d-flex justify-content-center" >
        {% if carts %}
        <!-- Editable table -->
            <div class="card cart-container w-100"  >
                 <div class="cart_section">
                    <div class="w-100">
                        <div class="row">
                            <div class="col-lg-10 offset-lg-1">
                                <div class="cart_container ">
                                    <div class="card-header text-left cart-header-text text-uppercase py-4">Shopping Cart ({{ carts.count }})</div>
                                    <span class=" float-right mb-3 mr-2"><a href="{% url "Shoppy:shoppy-home" %}" class="btn btn-outline-warning">Continue Shopping</a></span>

                                    <div class="cart_items bg-white " style="overflow-y: auto; overflow-scrolling: auto;">

                                        <ul class="cart_list">
                                            {% for cart in carts %}
                                                <li class=" {% if forloop.counter|divisibleby:2 %} animated fadeInLeftBig {% else %} animated fadeInRightBig {% endif %} cart_item clearfix" style="border-bottom: 1px solid #737373;">
                                                    <div class="cart_item_image m-0 position-relative">
                                                        <a href="{% url 'Shoppy:shoppy_product_details' cart.product.id %}"></a>
                                                        <img class="w-100 h-100 rounded" src="{{ cart.product.featured_url.url }}" alt="">
                                                        {% if cart.product.id|product_on_offer %}
                                                            {% for offer in cart.product.id|product_on_offer %}
                                                                <span style="position: absolute; left: 33px;transform: translateX(-55px);" class="badge badge-danger badge-pill text-white">Save {{ offer.offer_percentage }}%</span>
                                                            {% endfor %}
                                                        {% endif %}
                                                    </div>
                                                    <div class="cart_item_info d-flex flex-md-row flex-column justify-content-between">
                                                        <div class="cart_item_name cart_info_col">
                                                            <div class="cart_item_title">Name</div>
                                                            <div class="cart_item_text mt-sm-0 mb-sm-3" >
                                                                <a class="text-dark" href="{% url 'Shoppy:shoppy_product_details' cart.product.id %}">
                                                                    {{ cart.product.name|title|truncatechars:17 }}
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <div class="cart_item_color cart_info_col ml-sm-2">
                                                            <div class="cart_item_title">Variants</div>
                                                            <div class="cart_item_text mt-sm-0 mb-sm-3">
                                                                <div class="dropdown">
                                                                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-paint-roller"></i>
                                                                    <span class="caret"></span></button>
                                                                    <ul class="dropdown-menu" style="left:-34px;">
                                                                    {% for variant in request|cart_variants:cart.id %}
                                                                        <li class="dropdown-submenu">
                                                                            <a class="text-capitalize p-3 text-dark" tabindex="-1" href="#">{{variant}}</a>

                                                                        </li>
            {#                                                            {% for cvo in variant.id|cart_v_options:cart.id%}#}
            {#                                                              <span><i class="fa fa-arrow-right"></i><a tabindex="-1" href="#">{{cvo}}</a></span>#}
            {#                                                             {% endfor %}#}
                                                                    {% endfor %}
                                                                    </ul>
                                                                  </div>
                                                            </div>
                                                        </div>
                                                        <div class="cart_item_quantity cart_info_col ml-sm-2">
                                                            <div class="cart_item_title">Quantity</div>
                                                            <div class="cart_item_text mt-sm-0 mb-sm-3">{{ cart.quantity }}</div>
                                                        </div>
                                                        <div class="cart_item_quantity cart_info_col ml-sm-2">
                                                            <div class="cart_item_title">Cart action</div>
                                                            <div class="cart_item_text mt-sm-0 mb-sm-3">
                                                                 <span class="">
                                                                    <a href="{% url 'Shoppy:add_to_wishlist2' cart.product.id request.path|make_safe %}" class="delete-button"><i class="far fa-heart"></i></a>
                                                                 </span>
                                                                 <span class="">
                                                                    <a href="{% url "Shoppy:shoppy_delete_cart_product" cart.id %}" class="delete-button"><i class="fas fa-trash"></i></a>
                                                                 </span>
                                                            </div>
                                                        </div>
                                                        <div class="cart_item_price cart_info_col ">
                                                            <div class="cart_item_title">Price</div>
                                                            <div class="cart_item_text mt-md-0 mt-lg-0 mt-xl-0 mt-sm-0" style="">
                                                                {% if  cart.product.price_after_offer and cart.product.id|product_on_offer %}
                                                                    <div style="display: flex;flex-direction: column;">
                                                                        <span class="w-100 mt-sm-0 mb-sm-3"> {{ cart.product.price_after_offer|floatformat|intcomma }} Kshs</span>
                                                                        <span class="striked-price text-muted w-100" style="display: inline-grid">{{ cart.product.unit_cost_inclusive_of_vat|floatformat|intcomma }} Kshs</span>
                                                                    </div>
                                                                {% else %}
                                                                        <span class="w-100 mt-sm-0 mb-sm-3" style="margin-bottom:10px"> {{ cart.product.unit_cost_inclusive_of_vat|floatformat|intcomma }} Kshs</span>
                                                                        <div>
                                                                            {% if cart.product.vat_status == 'VAT' %}
                                                                                <p class="badge badge-danger badge-pill mr-0" style="transform: translateY(-12px);">VAT +</p>

                                                                                16% * ({{cart.product.unit_cost}})
                                                                            {% endif %}
                                                                        </div>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                        <div class="cart_item_total cart_info_col">
                                                            <div class="cart_item_title">Total</div>
                                                            <div class="cart_item_text mt-sm-0 mb-sm-3">

                                                                {{ cart.total|floatformat|intcomma }} Kshs

                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                    <!-- Order Total -->
                                    <div class="order_total">
                                        <div class="order_total_content text-md-right">
                                            <div class="order_total_title">Grand Total:</div>
                                            {% if request.user.is_authenticated %}
                                                <div class="order_total_amount">{{buyer.cart_total|floatformat|intcomma}} Ksh</div>
                                            {% else %}
                                                <div class="order_total_amount">{{total|floatformat|intcomma}} Ksh</div>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="cart_buttons">

            {#							<button type="button" class="button cart_button_clear">Add to Cart</button>#}
                                        {% if request.user.is_authenticated %}
                                            <a href="{% url 'Shoppy:shoppy-view_checkout' %}"  class="button animated rubberBand cart_button_checkout bg-org">CheckOut</a>
                                        {% else %}
                                            <a href="javascript:void(0);" onclick="alert_a_login(this);"  class="button animated rubberBand cart_button_checkout bg-org">CheckOut</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- Editable table -->
        {% else %}
            <div class="card cart-container w-100">
              <h3 class="card-header text-left cart-header-text text-uppercase py-4">Cart (0)</h3>
              <div class="card-body cart-table-body">
                <div id="table" class="table-editable">
                  <span class=" float-right mb-3 mr-2"><a href="{% url "Shoppy:shoppy-home" %}" class="btn btn-outline-warning">Continue Shopping</a>
                  </span>
                    <div class="row mt-2 d-flex justify-content-center align-content-center align-items-center">
                         <div class="col-sm-6" style="width: 200px; border: none;margin: 20px; overflow: hidden;">
                             <h1 class="text-center py-5 d-block w-100">No Cart For You Today</h1>

                         </div>
                    </div>
                </div>
              </div>
            </div>

        {% endif %}
    </div>

{% block scripts %}

    <script>
        $(document).ready(function(){
          $('.dropdown-submenu a.test').on("click", function(e){
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
          });
        });

        function alert_a_login(e){
             swal.fire({
                title: "Login",
                text: 'Please Login To Continue',
                type: "error",
                confirmButtonText: "Retry"
            });
             setInterval(function () {
                 window.location='/login';
             },2000)
        }
    </script>
{% endblock %}


{% endblock content %}

shoppy/templates/shoppy/login.html
{% extends 'shoppy/layout.html' %}

{% block content %}
    <div class="container">
<div class="forms-background col-sm-12 col-md-10 col-lg-10 mx-auto" >
      <div class=" content-section animated flipInX">


            <h2 class="py-4">Log in</h2>
            <form action="{% url 'Shoppy:shoppy-login' %}" method="post">
                {% csrf_token %}
                    <div class=" col-md-12 mb-3">
                      <label for="validationCustomUsername">Phonenumber</label>
                      <div class="input-group">
                        <div class="input-group-prepend bg-warning">
                          <span class="input-group-text bg-warning" id="inputGroupPrepend">@</span>
                        </div>
                        <input name="username" type="text" class="form-control" id="validationCustomUsername" placeholder="PhoneNumber or Username" aria-describedby="inputGroupPrepend" required><br>

                        <div class="invalid-feedback">
                          Please enter your Email.
                        </div>
                        <div class="valid-feedback">
                          Looks fantastic.
                        </div>
                      </div>
                    </div>

                    <div class="col-md-12 mb-3">
                          <label for="validationCustom04">Pin</label>
                          <div class="position-relative">
                                <input maxlength="4" type="password" name="password" class="form-control position-relative w-100 password1" id="validationCustom04" placeholder="Pin" required>
                               <div style="position: absolute;top: 9px;right: 11px;" class="password_checker">
                                    <i onclick="changeText1();" class="fas fa-eye txt1 color animation "></i>
                                    <i style="display:none;" onclick="changePassword1();" class="fas fa-eye-slash psd1 color animation "></i>
                               </div>
                          </div>
                          <div class="invalid-feedback">
                            Please provide a valid state.
                          </div>
                          <div class="valid-feedback">
                            Better looking.
                          </div>
                    </div>


                  <button class="product-button" type="submit">Log in</button>
            </form>
            <div class=" pt-3">
                <small class="text-muted medium-text">
                    Need an account? <a href="{% url 'Shoppy:shoppy-buyer-reg' %}" class="ml-2">Sign up</a>
                </small>
            </div>
            <div class=" pt-3">
                <small class="text-muted medium-text">
                    Forgot Pin? <a href="{% url 'Shoppy:password_resett' %}" class="ml-2">Reset</a>
                </small>
            </div>

      </div>
</div>
    </div>
{% endblock content %}
{% block scripts %}
    <script>
     var pswd1 = document.getElementsByClassName('password1')[0];
        var txt1 = document.getElementsByClassName('txt1')[0];
        var psd1 = document.getElementsByClassName('psd1')[0];
        function changeText1() {

            pswd1.setAttribute('type','text');
            psd1.style.display="block";
            txt1.style.display = "none";
            txt1.style.transition = 1+"s";
        }
        function changePassword1() {
            pswd1.setAttribute('type','password');
            psd1.style.display="none";
            txt1.style.display = "block";
            txt1.style.transition = 1+"s";
        }
    </script>
{% endblock scripts %}