django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('shoppy.urls')),
    path('admin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('', views.home, name='shoppy-home'),

   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list/<int:category_id>/', views.productsList, name='product_list'),
   path('allcategoryproductsList/', views.allcategoryproductsList, name='allcategoryproductsList'),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),
   path('placeholder/' , views.placeholder, name="placeholder" ),

   path('howtopay/', views.how_to_pay, name='how_to_pay'),

   path('product_filter/', views.product_filter, name='product_filter'),





   #wishlist
   path('add_to_wishlist/' , views.addToWishlist, name='add_to_wishlist' ),
   path('add_to_wishlist2/<int:product_id>/<str:source>/' , views.addToWishlist2, name='add_to_wishlist2' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         # path('make_reviews/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<str:source>/', views.addCart, name='shoppy-add-cart'),
   # path('addto/cartsession/', views.addCartSession, name='shoppy-add-cartSession'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset

   path('pin_reset/', views.password_resett, name='password_resett'),
   path('getpinShortcode/', views.getShortcode, name='getpinShortcode'),
   path('verifyCode/', views.verifyCode, name='verifyCode'),
   path('verifypassword/', views.verifypassword, name='verifypassword'),
   path('pin_confirm/', views.pin_confirmm, name='password_confirmm'),
   path('new_pin/', views.new_pin, name='new_pin'),




   path('deleteme/', views.deleteme, name= 'deleteme'),
   path('check_voucher_if_it_exists/', views.check_voucher_if_it_exists, name= 'check_voucher_if_it_exists'),


   path('all_buyers_orders/', views.all_buyers_orders, name= 'all_buyers_orders'),
   path('all_buyers_order_products/<str:reference_code>', views.all_buyers_order_products, name= 'all_buyers_order_products'),
   path('orders_payment_opions/<int:checkout_id>', views.orders_payment_opions, name= 'orders_payment_opions'),





]

shoppyadmin/urls.py
from django.urls import path
from .views import GeneratePDF, ListUsers, GenerateProductPDF,  ListOrdersadmin

from . import views

app_name = 'ShoppyAdmin'
urlpatterns = (

   path('', views.home, name='shoppy-admin-home'),
   path('sellers/', views.sellers, name='shoppy-admin-sellers'),
   path('orders/', views.orders, name='shoppy-admin-orders'),
   path('login/', views.user_login, name='shoppy-admin-login'),
   path('all/productsreviews/', views.reviews, name='shoppy-admin-reviews'),
   path('singleproduct/review/<int:product_id>/', views.single_product_review, name='single_product_review'),
   path('buyers/', views.buyers, name='shoppy-admin-buyers'),
   path('useraccount/', views.userAccount, name='shoppy-user-account'),
   path('adminaccount/', views.adminAccount, name='shoppy-admin-account'),
   path('useraccount/changepassword/', views.changepassword, name='shoppy-changepassword'),

   path('payments/', views.payments, name='shoppy-payments'),
   path('editpayments/<int:Order_payment_id>', views.edit_payments, name='shoppy_updated_payments'),
   path('buyerOrders/<str:reference_code>', views.buyerOrders, name='shoppy-buyer_orders'),
   path('buyerOrdersCancel/<str:reference_code>', views.buyerOrdersCancel, name='shoppy-buyer_orders_cancel'),
     # extras
      path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
      path('xcel/orders/', views.export_users_xls, name='export_users_xl'),
      path('xcel/orders/date', views.export_users_xls_date, name='export_users_xl_date'),
      path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),
      path('users/chart/', ListUsers.as_view(), name='users_chart'),
      path('orders/chart/', views.ListOrders, name='orders_chart'),
      path('orders/chart/admin', ListOrdersadmin.as_view(), name='orders_chartadmin'),
     # extras
   # seller
   path('seller_status/<int:seller_id>', views.sellerStatusChange, name='shoppy-admin-status-change'),

   #products
   path('view/products/', views.view_all_products, name="shoppy_admin_view_all_products"),
   path('view/all/products/', views.view_products, name="view_products"),
   # path('filter_products/', views.fillter_products_per_seller, name="fillter_products_per_seller"),

   path('edit/product/<int:product_id>', views.edit_product, name="shoppy_admin_edit_product"),
   path('delete/product/<int:product_id>', views.product_delete, name='product_delete'),

   #featuredProducts
   path('products/featured/products', views.featured_products, name='featuredproduct'),
   path('featured/product/change/status/featured/<int:product_id>', views.featured_products_featured, name='featured_products'),
   path('featured/product/change/status/normal/<int:product_id>', views.normal_products_normal, name='nomal_products'),
   path('featured/product/change/status/', views.product_featured, name='product_featured'),

   path('products/verified/<int:product_id>/', views.verify_product, name='verify_product'),
   path('products/unverified/<int:product_id>/', views.unverify_product, name='unverify_product'),
   path('products/verification/', views.product_verification, name='product_verification'),

   #category
   path('view_category/', views.view_category, name='shoppy_admin_add_category'),
   path('addingcategory/', views.addingcategory, name='shoppy_adding_category'),
   path('deletecategory/<int:category_id>', views.deletecategory, name='shoppy_delete_category'),
   path('editcategory/<int:category_id>', views.editcategory, name='shoppy_edit_category'),
   path('view_sub_category/<int:category_id>', views.view_sub_category, name='shoppy_view_sub_category'),


   # brand
   path('add_brand/', views.add_brand, name='shoppy_admin_add_brand'),
   path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
   path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),

   #image
   path('delete/image/<int:image_id>', views.image_delete, name='delete_product_image'),

   #regions
   path('viewregions/', views.view_regions, name='shoppy-admin-view-regions'),
   path('regions/edit/<int:region_id>', views.edit_regions, name='shoppy-admin-edit-regions'),
   path('regions/delete/<int:region_id>', views.delete_regions, name='shoppy-admin-delete-regions'),

   #carousell
   path('view/carousel/', views.view_carousel, name='view_carousel'),
   path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),
   path('carousel/edit/<int:carousel_id>', views.carousel_edit, name='carousel-edit'),

   #variants
   path('variants/', views.variants, name='variants'),
   path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
   path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   #variant options
   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

   # offer
   path('offers/', views.offer, name='view_product_offer'),
   path('addOffer/',views.addOffer, name="adding_offers"),
   path('editOffer/<int:offer_id>',views.editOffer, name="edit_offers"),
   path('deleteOffer/<int:offer_id>',views.deleteOffer, name="delete_offer"),

   # reports
   path('allreports/', views.viewAllReports, name='view_all_reports'),

   #inventory
   path('updateInventory/<int:product_id>', views.update_Inventory, name='updateInventory'),
   # voucher
   path('voucher/', views.voucher, name='voucher'),
   path('addvoucher/', views.addvoucher, name='addvoucher'),
   path('deletevoucher/<int:voucher_id>', views.deletevoucher, name='deletevoucher'),
   path('editvoucher/<int:voucher_id>', views.editvoucher, name='editvoucher'),

)

shoppyadmin/models.py
from django.db import models

# Create your models here.

shoppyadmin/templates/regions/regions.html
6{% extends 'aaa_layout.html' %}
{% load static %}
{% load humanize %}
{% block links %}
{#    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">#}
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

{% endblock links %}
{% block content %}
 <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li>
                <a href="#">
                <em class="fa fa-home"></em>
                </a>
            </li>
            <li class="active">Regions</li>
        </ol>
    </div><!--/.row-->
   <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Regions</h1>
        </div>
   </div><!--/.row-->
                    {% for region in regions %}
                    <!-- Modal -->
                    <div class="modal fade" id="{{ region.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                      <div class="modal-dialog" >
                        <div class="modal-content modal-dialog-centered">
                          <div class="modal-header bg-orange-shoppy">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title text-white" id="myModalLabel">Edit Regions</h4>
                          </div>
                          <div class="modal-body">
                            <form action="{% url 'ShoppyAdmin:shoppy-admin-edit-regions' region.id %}" method="POST" >
                                {% csrf_token %}
                                <div class="input-group col-sm-12 marginY" >
                                   <div class="form-group">
                                        <label class="custom-control" for=region_name">Region:</label>
                                        <input value="{{ region.name }}" placeholder="Region Name" name="name" type="text" class="form-control" id="region_name">
                                   </div>
                                </div>
                                <div class="input-group col-sm-12 marginY">
                                   <div class="form-group">
                                        <label class="custom-control" for="region_cost">Region Cost</label>
                                        <input value="{{ region.region_cost }}" name="region_cost" placeholder="Region Destination cost"  type="number" class="form-control" id="region_cost" required>
                                   </div>
                                </div>
                                <button type="submit" class="btn btn-success marginY"><i class="fas fa-file"></i> Save</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>

                            </form>
                          </div>

                        </div>
                      </div>
                    </div>
                    {% endfor %}
   <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading panel-warning-custom">
                       All Regions

                        <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
                    <div class="panel-body">
                        <div class="canvas-wrapper">
                            <div class="main-chart" id="line-chart" height="200" width="600">
                                <form action="{% url 'ShoppyAdmin:shoppy-admin-view-regions' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="input-group col-sm-12 marginY" >
                                       <div class="form-group">
                                            <label class="custom-control" for=region_name">Region:</label>
                                            <input placeholder="Region Name" name="name" type="text" class="form-control" id="region_name">
                                       </div>
                                    </div>
                                    <div class="input-group col-sm-12 marginY">
                                       <div class="form-group">
                                            <label class="custom-control" for="region_cost">Region Cost</label>
                                            <input name="region_cost" placeholder="Region Destination cost"  type="number" class="form-control" id="region_cost" required>
                                       </div>
                                    </div>
{#                                    <div class="form-group has-feedback  col-sm-12">#}
{#                                      <label for="sel3">Seller</label> <br>#}
{#                                      <select required name="seller" id="sel3" class="selectpicker" data-show-subtext="true" data-live-search="true">#}
{#                                        <option value="">Choose A Seller</option>#}
{#                                        {% for seller in sellers %}#}
{#                                         <option data-subtext="{{ seller.first_name }}" value="{{ seller.id }}">{{ seller.first_name }}{{ seller.last_name }}</option>#}
{#                                        {% endfor %}#}
{#                                      </select>#}
{#                                    </div>#}
                                    <button type="submit" class="btn btn-success marginY"><i class="fas fa-plus-circle"></i> Add</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.row-->

   <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading panel-warning-custom">
                         All Regions
                        <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
                    <div class="panel-body">
                        <div class="canvas-wrapper">
                            <div class="main-chart" id="line-chart" height="200" width="600">
                                <table id="" class="example table table-striped table-bordered" style="width:100%;">
                                    <thead>
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Region Cost</th>
                                            <th>Created At</th>
                                            <th>Updated At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for region in regions %}
                                            <tr class="text-center ">
                                                <td class="tb-data">{{ region.id }}</td>
                                                <td class="tb-data font-weight-bolder text-capitalize">{{ region.name }}</td>
                                                <td class="tb-data">{{ region.region_cost|floatformat:1|intcomma }} Ksh</td>
                                                <td class="tb-data">{{ region.created_at }}</td>
                                                <td class="tb-data">{{ region.updated_at }}</td>
                                                <td class="tb-data">
                                                    <a data-toggle="modal" data-target="#rd{{ region.id }}" href="#" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
                                                    <a data-toggle="modal" data-target="#{{ region.id }}" href="{% url 'ShoppyAdmin:shoppy-admin-edit-regions' region.id %}" class="btn btn-success" >
                                                        <i class="fas fa-pencil-alt"></i> Edit
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

              {% for region in regions %}
              <!-- Modal -->
              <div class="modal fade " id="rd{{ region.id }}" role="dialog">
                <div class="modal-dialog modal-sm ">
                  <div class="modal-content ">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Region Delete Confirmation</h4>
                    </div>
                    <div class="modal-body">
                      <h4>Are you sure you want to delete {{ region.name }} </h4>
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'ShoppyAdmin:shoppy-admin-delete-regions' region.id %}" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

        </div><!--/.row-->

</div>




{% endblock %}
{% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
{#    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>#}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.example').DataTable();
        } );
    </script>
{% endblock scripts %}