django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('', include('shoppy.urls')),
    path('admin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('', views.home, name='shoppy-home'),

   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list/<int:category_id>/', views.productsList, name='product_list'),
   path('allcategoryproductsList/', views.allcategoryproductsList, name='allcategoryproductsList'),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),
   path('placeholder/' , views.placeholder, name="placeholder" ),

   path('howtopay/', views.how_to_pay, name='how_to_pay'),

   path('product_filter/', views.product_filter, name='product_filter'),





   #wishlist
   path('add_to_wishlist/' , views.addToWishlist, name='add_to_wishlist' ),
   path('add_to_wishlist2/<int:product_id>/<str:source>/' , views.addToWishlist2, name='add_to_wishlist2' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         # path('make_reviews/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<str:source>/', views.addCart, name='shoppy-add-cart'),
   # path('addto/cartsession/', views.addCartSession, name='shoppy-add-cartSession'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset

   path('pin_reset/', views.password_resett, name='password_resett'),
   path('getpinShortcode/', views.getShortcode, name='getpinShortcode'),
   path('verifyCode/', views.verifyCode, name='verifyCode'),
   path('verifypassword/', views.verifypassword, name='verifypassword'),
   path('pin_confirm/', views.pin_confirmm, name='password_confirmm'),
   path('new_pin/', views.new_pin, name='new_pin'),




   path('deleteme/', views.deleteme, name= 'deleteme'),
   path('check_voucher_if_it_exists/', views.check_voucher_if_it_exists, name= 'check_voucher_if_it_exists'),


   path('all_buyers_orders/', views.all_buyers_orders, name= 'all_buyers_orders'),
   path('all_buyers_order_products/<str:reference_code>', views.all_buyers_order_products, name= 'all_buyers_order_products'),
   path('orders_payment_opions/<int:checkout_id>', views.orders_payment_opions, name= 'orders_payment_opions'),





]

shoppyadmin/urls.py
from django.urls import path
from .views import GeneratePDF, ListUsers, GenerateProductPDF,  ListOrdersadmin

from . import views

app_name = 'ShoppyAdmin'
urlpatterns = (

   path('', views.home, name='shoppy-admin-home'),
   path('sellers/', views.sellers, name='shoppy-admin-sellers'),
   path('orders/', views.orders, name='shoppy-admin-orders'),
   path('login/', views.user_login, name='shoppy-admin-login'),
   path('all/productsreviews/', views.reviews, name='shoppy-admin-reviews'),
   path('singleproduct/review/<int:product_id>/', views.single_product_review, name='single_product_review'),
   path('buyers/', views.buyers, name='shoppy-admin-buyers'),
   path('useraccount/', views.userAccount, name='shoppy-user-account'),
   path('adminaccount/', views.adminAccount, name='shoppy-admin-account'),
   path('useraccount/changepassword/', views.changepassword, name='shoppy-changepassword'),

   path('payments/', views.payments, name='shoppy-payments'),
   path('editpayments/<int:Order_payment_id>', views.edit_payments, name='shoppy_updated_payments'),
   path('buyerOrders/<str:reference_code>', views.buyerOrders, name='shoppy-buyer_orders'),
   path('buyerOrdersCancel/<str:reference_code>', views.buyerOrdersCancel, name='shoppy-buyer_orders_cancel'),
     # extras
      path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
      path('xcel/orders/', views.export_users_xls, name='export_users_xl'),
      path('xcel/orders/date', views.export_users_xls_date, name='export_users_xl_date'),
      path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),
      path('users/chart/', ListUsers.as_view(), name='users_chart'),
      path('orders/chart/', views.ListOrders, name='orders_chart'),
      path('orders/chart/admin', ListOrdersadmin.as_view(), name='orders_chartadmin'),
     # extras
   # seller
   path('seller_status/<int:seller_id>', views.sellerStatusChange, name='shoppy-admin-status-change'),

   #products
   path('view/products/', views.view_all_products, name="shoppy_admin_view_all_products"),
   path('view/all/products/', views.view_products, name="view_products"),
   # path('filter_products/', views.fillter_products_per_seller, name="fillter_products_per_seller"),

   path('edit/product/<int:product_id>', views.edit_product, name="shoppy_admin_edit_product"),
   path('delete/product/<int:product_id>', views.product_delete, name='product_delete'),

   #featuredProducts
   path('products/featured/products', views.featured_products, name='featuredproduct'),
   path('featured/product/change/status/featured/<int:product_id>', views.featured_products_featured, name='featured_products'),
   path('featured/product/change/status/normal/<int:product_id>', views.normal_products_normal, name='nomal_products'),
   path('featured/product/change/status/', views.product_featured, name='product_featured'),

   path('products/verified/<int:product_id>/', views.verify_product, name='verify_product'),
   path('products/unverified/<int:product_id>/', views.unverify_product, name='unverify_product'),
   path('products/verification/', views.product_verification, name='product_verification'),

   #category
   path('view_category/', views.view_category, name='shoppy_admin_add_category'),
   path('addingcategory/', views.addingcategory, name='shoppy_adding_category'),
   path('deletecategory/<int:category_id>', views.deletecategory, name='shoppy_delete_category'),
   path('editcategory/<int:category_id>', views.editcategory, name='shoppy_edit_category'),
   path('view_sub_category/<int:category_id>', views.view_sub_category, name='shoppy_view_sub_category'),


   # brand
   path('add_brand/', views.add_brand, name='shoppy_admin_add_brand'),
   path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
   path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),

   #image
   path('delete/image/<int:image_id>', views.image_delete, name='delete_product_image'),

   #regions
   path('viewregions/', views.view_regions, name='shoppy-admin-view-regions'),
   path('regions/edit/<int:region_id>', views.edit_regions, name='shoppy-admin-edit-regions'),
   path('regions/delete/<int:region_id>', views.delete_regions, name='shoppy-admin-delete-regions'),

   #carousell
   path('view/carousel/', views.view_carousel, name='view_carousel'),
   path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),
   path('carousel/edit/<int:carousel_id>', views.carousel_edit, name='carousel-edit'),

   #variants
   path('variants/', views.variants, name='variants'),
   path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
   path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   #variant options
   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

   # offer
   path('offers/', views.offer, name='view_product_offer'),
   path('addOffer/',views.addOffer, name="adding_offers"),
   path('editOffer/<int:offer_id>',views.editOffer, name="edit_offers"),
   path('deleteOffer/<int:offer_id>',views.deleteOffer, name="delete_offer"),

   # reports
   path('allreports/', views.viewAllReports, name='view_all_reports'),

   #inventory
   path('updateInventory/<int:product_id>', views.update_Inventory, name='updateInventory'),
   # voucher
   path('voucher/', views.voucher, name='voucher'),
   path('addvoucher/', views.addvoucher, name='addvoucher'),
   path('deletevoucher/<int:voucher_id>', views.deletevoucher, name='deletevoucher'),
   path('editvoucher/<int:voucher_id>', views.editvoucher, name='editvoucher'),

)

shoppyadmin/models.py
from django.db import models

# Create your models here.

shoppyadmin/templates/brand and category/brand.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
     <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

{% endblock links %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row ">
			<ol class="breadcrumb">
				<li>
					<a href="#">
					<em class="fa fa-home"></em>
				    </a>
			    </li>
				<li class="active">Brand</li>
			</ol>
		</div><!--/.row-->
        <div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Brands</h1>
			</div>
		</div><!--/.row-->
        <div class="row">
            <div class="col-md-12">
				<div class="panel panel-default ">
					<div class="panel-heading">
						Brand

						<span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
                        <a href="#" data-toggle="modal" data-target="#add_brand" class="btn btn-success pull-right">Add Brand</a>
                    </div>
					<div class="panel-body" >
                        <table id="example" class="table table-striped table-bordered" style="width:100%;">
                            <thead >

                                <tr class="text-capitalize">
                                    <th>Id</th>
                                    <th>Name</th>
{#                                    <th>Category</th>#}
                                    <th>Date Created</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                    {% for brand in brands %}
                                        <tr>
                                            <td class="tb-data">{{ forloop.counter }}</td>
                                            <td class="tb-data">{{ brand.name }}</td>
{#                                            <td>{{ brand.category.name }}</td>#}
{#                                            {% for category in categories %}#}
{#                                                {% if category.id == brand.id %}#}
{#                                                   <td class="tb-data">{{ category.name}}</td>#}
{#                                                {% endif %}#}
{#                                            {% endfor %}#}
                                            <td class="tb-data">{{ brand.created_at }}</td>
                                            <td class="text-center tb-data">
                                                <a href="#" data-toggle="modal" data-target="#delete{{ brand.id }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                                                <a href="#" data-toggle="modal" data-target="#{{ brand.id }}" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Edit</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
					</div>
				</div>
            </div>
        </div>


        <!-- Modaladd_brand -->
            <div class="modal fade" id="add_brand" role="dialog">
            <div class="modal-dialog modal-md">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Add Brand</h4>
                </div>
                <div class="modal-body">
                 <fieldset>
                     <form action="{% url 'ShoppyAdmin:shoppy_admin_add_brand' %}" method="POST">
                     {% csrf_token %}
                         <div class="form-group has-success has-feedback">
                          <label class="control-label" for="brand">Brand Name</label>
                          <input type="text" class="form-control" name="name" id="brand" aria-describedby="inputSuccess2Status" required>
                          <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                          <span id="inputSuccess2Status" class="sr-only">(success)</span>
                        </div>

                        <div class="paddingy2">
                            <button type="submit" class="btn bg-orange">  Add</button>
{#                            <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>#}
                        </div>
                     </form>
                 </fieldset>
                </div>
              </div>
            </div>
          </div>
            {% for brand in brands %}
                <!--delete confirm Modal -->
              <div class="modal fade" id="delete{{ brand.id }}" role="dialog">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title text-capitalize">Deleting {{ brand.name }}</h4>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure you want to delete {{ brand.name }}.</p>
                    </div>
                    <div class="modal-footer">
{#                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
                        <a class="btn btn-danger" href="{% url 'ShoppyAdmin:delete_brand' brand.id %}"> Delete </a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          <!-- Small modal edit_modal -->
              {% for brand in brands %}
              <div class="modal fade" id="{{ brand.id }}" role="dialog">
                <div class="modal-dialog modal-md">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 style="text-transform: capitalize" class="modal-title">Edit Brand {{ brand.name }}</h4>
                    </div>
                    <div class="modal-body">
                         <form action="{% url 'ShoppyAdmin:brand_edit' brand.id %}" method="POST">
                         {% csrf_token %}

                             <div class="form-group has-success has-feedback">
                              <label class="control-label" for="brand">Brand Name</label>
                              <input value="{{ brand.name }}" type="text" class="form-control" name="name" id="brand" aria-describedby="inputSuccess2Status" required>
                            </div>

                            <div class="paddingy2">
                                <button type="submit" class="btn bg-orange"><i class="fas fa-file"></i> Save</button>
    {#                         <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i>Close</button>#}
                            </div>
                         </form>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}



    </div>

{% endblock %}

{% block scripts %}
   <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
   </script>
   <script>
        $(function() {
          $('.selectpicker').selectpicker();
        });
   </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock scripts %}

shoppyadmin/templates/brand and category/category.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

{% endblock links %}
{% block content %}
     <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li>
					<a href="#">
					<em class="fa fa-home"></em>
				    </a>
			    </li>
				<li class="active">Category</li>
			</ol>
		</div><!--/.row-->
       <div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Category</h1>
			</div>
		</div><!--/.row-->

            <!-- Add Category Modal -->
                <div class="modal fade" id="addCategory" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                       <fieldset>
                             <form action="{% url 'ShoppyAdmin:shoppy_adding_category' %}" method="POST">
                             {% csrf_token %}
                                 <div class="form-group has-success has-feedback">
                                  <label class="control-label" for="brand">Category Name</label>
                                  <input autofocus autocapitalize="on" type="text" class="form-control" name="name" id="brand" aria-describedby="inputSuccess2Status" required>
                                  <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                                  <span id="inputSuccess2Status" class="sr-only">(success)</span>
                                </div>
                                <div class="form-group has-feedback  col-sm-12">
                                  <label for="sel1">Category</label> <br>
                                  <select name="parent_id" class="selectpicker" data-show-subtext="true" data-live-search="true">
                                    <option selected value="">Choose A Category</option>
                                    {% for category in categories %}
                                     <option data-subtext="{{ category.name }}" value="{{ category.id }}">{{ category.name }}</option>
                                    {% endfor %}
                                  </select>
                                </div>
                                <div class="paddingy2">
                                    <button type="submit" class="btn btn-success"> <i class="fas fa-plus"></i> Add</button>
                                    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>
                                </div>
                             </form>
                       </fieldset>
                      </div>
{#                      <div class="modal-footer">#}
{#                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                        <button type="button" class="btn btn-primary">Save changes</button>#}
{#                      </div>#}
                    </div>
                  </div>
                </div>
        <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-warning-custom">
                            Main Categories

                            <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span>
                            <a href="#" data-toggle="modal" data-target="#addCategory" class="btn btn-success pull-right">Add Category</a>
                        </div>


                        <div class="panel-body">
                            <div class="canvas-wrapper">
                                <div class="main-chart" id="line-chart" height="200" width="600">
                                    <table id="example" class="table table-striped table-bordered" style="width:100%;">
                                    <thead>
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Created At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for category in categories %}
                                            <tr class="text-center ">
                                                <td class="tb-data">{{ category.id }}</td>
                                                <td class="tb-data text-capitalize">{{ category.name }} ({{ category.childern_count }})</td>
                                                <td class="tb-data">{{ category.created_at }}</td>
                                                <td class="tb-data">
                                                    {% if category.has_children %}
                                                    <a href="{% url "ShoppyAdmin:shoppy_view_sub_category" category.id %}" class="btn btn-info"><i class="fas fa-eye"></i> View</a>
                                                    {% endif %}
                                                    <a href="" data-toggle="modal" data-target="#delete{{ category.id }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                                                    <a href="" data-toggle="modal" data-target="#editcategory{{ category.id }}" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Edit</a>
                                                </td>
                                            </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% for category in categories %}
                <!--delete confirm Modal -->
              <div class="modal fade" id="delete{{ category.id }}" role="dialog">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title text-capitalize">Deleting {{ category.name }}</h4>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure you want to delete {{ category.name }}.</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <a class="btn btn-danger" href="{% url "ShoppyAdmin:shoppy_delete_category" category.id %}"> Delete </a>
                    </div>
                  </div>
                </div>
              </div>
        {% endfor %}
        {% for category in categories %}
                <!--edit confirm Modal -->
              <div class="modal fade" id="editcategory{{ category.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Category {{ category.name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                       <fieldset>
                             <form action="{% url 'ShoppyAdmin:shoppy_edit_category' category.id %}" method="POST">
                             {% csrf_token %}
                                 <div class="form-group has-success has-feedback">
                                  <label class="control-label" for="brand">Category Name</label>
                                  <input value="{{ category.name }}" type="text" class="form-control" name="name" id="brand" aria-describedby="inputSuccess2Status" required>
                                  <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                                  <span id="inputSuccess2Status" class="sr-only">(success)</span>
                                </div>
                                <div class="form-group has-feedback  col-sm-12">
                                  <label for="sel1">Category</label> <br>
                                  <select name="parent_id" class="selectpicker" data-show-subtext="true" data-live-search="true">
                                        {% if category.id == category.parent_id_id %}
                                           <option selected value="">{{ category.name }}</option>
                                            {% else %}
                                           <option selected value="">No Parent</option>
                                        {% endif %}
                                    {% for category in categories %}
                                     <option data-subtext="{{ category.name }}"
                                             value="{{ category.id }}">
                                                {{ category.name }}
                                     </option>
                                    {% endfor %}
                                  </select>
                                </div>
                                <div class="paddingy2">
                                    <button type="submit" class="btn btn-success"> <i class="fas fa-plus"></i> Save</button>
                                    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>
                                </div>
                             </form>
                       </fieldset>
                      </div>
{#                      <div class="modal-footer">#}
{#                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                        <button type="button" class="btn btn-primary">Save changes</button>#}
{#                      </div>#}
                    </div>
                  </div>
                </div>

        {% endfor %}

      </div><!--/.row-->
    </div>
{% endblock content %}
{% block scripts %}

    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>

{% endblock scripts %}